apiVersion: v1
kind: Namespace
metadata:
  name: langfuse-test
---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-app-secret
  namespace: langfuse-test
type: Opaque
stringData:
  salt: "WV2CX7tDu7UCYf+fFqhIK4fZBXxTPZEdLncmT3H2Dgs=" # dummy value for testing
  nextauth-secret: "GgJvzB0kbkhiLyokbwRXBpgea2+Iq9y+EqBPCSfXbLc=" # dummy value for testing
  encryption-key: "089e984b49de89804c9c3862d039a42363e6a8578d5ff7a64fe5d4de9950326b" # dummy value for testing
---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-postgres-secret
  namespace: langfuse-test
type: Opaque
stringData:
  postgres-password: "langfuse-postgres-password"
  # Connection string will be constructed by Langfuse based on deployed PostgreSQL service
  postgres-connection-string: "postgresql://langfuse:langfuse-postgres-password@langfuse-postgresql:5432/langfuse"
---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-redis-secret
  namespace: langfuse-test
type: Opaque
stringData:
  redis-password: "langfuse-redis-password"
  # Connection string for Redis deployed by the chart
  redis-connection-string: "redis://:langfuse-redis-password@langfuse-redis-master:6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-clickhouse-secret
  namespace: langfuse-test
type: Opaque
stringData:
  clickhouse-password: "langfuse-clickhouse-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-minio-secret
  namespace: langfuse-test
type: Opaque
stringData:
  root-user: "minioadmin"
  root-password: "langfuse-minio-password"
